project:
  imagetype: FILE
  imageUrl: http://127.0.0.1:8086
  imagedir: D:/exco/backend-webapp-img
  secure:
    rsaPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgzm+YfBVi+hemicHMLE/tcr5Wegx2x/E9H+/0Axfy0X6u5hjjRNnP6HdpH43PZz0VN/V+SIW9J9aPT5OoKbHRCBF7CGQI678HE9nXuZ4CM453aX2r6pkBVlbL0a7jrAr41QBWaj0RODH+l41glVuzY1j8MPHpgUV3qHt38eGdyyIGstHOA1zJeCqV/J2ewbB9rTiLmM4yXMMuSX1+Ayvq/oqfZ57lmK82SKIp90p3PVbnMxRKbXnyEgJwXTjnQya8q5iPkaythjti8uhodc7BOM/S8UoS2MU/15TzjHDhMTh48+pBzyPtbV9fAHJpXfd88Unh0B+cNRdm0eYD+k3swIDAQAB
    rsaPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCDOb5h8FWL6F6aJwcwsT+1yvlZ6DHbH8T0f7/QDF/LRfq7mGONE2c/od2kfjc9nPRU39X5Ihb0n1o9Pk6gpsdEIEXsIZAjrvwcT2de5ngIzjndpfavqmQFWVsvRruOsCvjVAFZqPRE4Mf6XjWCVW7NjWPww8emBRXeoe3fx4Z3LIgay0c4DXMl4KpX8nZ7BsH2tOIuYzjJcwy5JfX4DK+r+ip9nnuWYrzZIoin3Snc9VuczFEptefISAnBdOOdDJryrmI+RrK2GO2Ly6Gh1zsE4z9LxShLYxT/XlPOMcOExOHjz6kHPI+1tX18Acmld93zxSeHQH5w1F2bR5gP6TezAgMBAAECggEAbDP15t38PAPb1bIuvJi61tTJ7LeIPI2iopSf/hXl+z/1si/CjnYcYZy/nL4yIIzF7yIuVmIkmYq4Jt20icVbc7JE1aMLLlFAMrvKmbbh7SjXEAukME8IcFyw0ne5ebuMRMNk5aBp4k2St8Bs0M5PMhDPApz8h8mTseLFuQrVtneEbB9lnuaDXjc2bWt3HfH2OzaEqDgnUdiyMHY5D6p4e6NHGGYrh0m/m0SSMZezWgmJ3LG4p1uBGrpmBGK2LwwdwowdeC5ZZPMG98E1PpUK+1hx4ccRfh3oOZ+Ij+H+T7hi5W6uOwYNbLidkCT9JN7EPaXYopQbtOC7WLwZOXWhsQKBgQC5x3GXBz/h3dv2vNzyEVxAFECOXzsK8fvlobc4LzdidjO4CCSNsE2JTfmoSJYN+ybNOH8TshfOWvY8+qGV1lXFAQAoU/z0VQ36tm5RoTozP22UAekjp9uwjHcij3TRu9ZrRCZpb9HY1nYlA4SDSG3koDuuCAQhQOc+yRl1tJEpiQKBgQC004iZMIXaShhldLsxZhWR58aNu9C8Ld1WJYYvEYxtPRJgzLjkslwFIJQgjq4NFrHfSjccRcGspck2+CzjeM/y/ETh48BdCQRChpKUNOI07iuOsWhzLunC3aetoYIvw7xwaL+FJ9oFMMRdCeAEpxpGRwGipyAP2bz1sbL0YhrUWwKBgDvhcVeA2rJu1GufTIgp2FY/MN+zClDo1oyZp3jQn0V5XApBdabF4PgUzhfT7anr/gG/6BXtHYdCAoR9NIAbaeHqBKb7C1ml4K+jBcQB98R0+VjvlLoNbN5nKC9XlgvUQ7SnbsolZLpDxikADUJTojhC/XmG0+30AZVXNIGgBfohAoGAMxJjzFCGHac7yLv1evhIM1NxIurfA6c4knI6ueSM8vWC0VBBEGbH0rLm42MpCY1VY6mEcznIf8i7Ugk6NG0U3p4dnmdDF4PKbjewAqgFE8oJB15YD+A6Kc2M5F9vc6om+OC85xDgZQLnExgM64N+ykaX0aa+SXvIAOTVlGx5A20CgYAVzAO7udHxYLI8e4KB8VLzsOQXPwpzreUnXqzJEIsMhyq25sRkgcr92qnsKB5sQVTOJyqjhKl9CIjsElQECn3v+Rwo+H0T3cFQJ7KHqPbS4JcHFmaQQX+8ZGaipydZsaYpmub4mlIG90wYfa8r8kxQPSm9tZEz77tUnfH5G66p+Q==
    aesPrivateKey: f3ffd4005918d4549918f24cc518e443


server:
  servlet:
    context-path: /
  port: 8083

spring:
  application:
    name: trading
  thymeleaf:
    cache: false
    #prefix: classpath:/views/
  favicon:
    enabled: false
  messages:
    basename: i18n/messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: xzpp123456
    url: jdbc:mysql://127.0.0.1:3306/cm_trade_db?useSSL=false&serverTimezone=UTC
    username: root

  jackson:
    default-property-inclusion: non_null

  jpa:
    show-sql: false
    hibernate:
      naming:
        # implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
      # temp:
      #   use_jdbc_metadata_defaults: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false

  redis:
    host: 127.0.0.1
    password: XZpp123456
    port: 6379
    pool:
      max-idle: 5
      max-total: 20
    timeout: 100000

topic:
  depth: msg-book50
  deal: msg-deal