server:
  servlet:
    context-path: /
  port: 8083

spring:
  application:
    name: trading
  thymeleaf:
    cache: false
    #prefix: classpath:/views/
  favicon:
    enabled: false
  messages:
    basename: i18n/messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: xzpp123456
    url: jdbc:mysql://127.0.0.1:3306/cm_trade_db?useSSL=false&serverTimezone=UTC
    username: root

  jackson:
    default-property-inclusion: non_null

  jpa:
    show-sql: false
    hibernate:
      naming:
        # implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
      # temp:
      #   use_jdbc_metadata_defaults: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false

  redis:
    host: 127.0.0.1
    password: XZpp123456
    port: 6379
    pool:
      max-idle: 5
      max-total: 20
    timeout: 100000
