/*
 * This file is generated by jOOQ.
 */
package com.cryptomind.wquote;


/**
 * K线步长
 */
public enum KlineStep {

    _1m("1m", KlineStepUtil.MINUTE_TYPE,1,KlineStepConstant.STEP_1_MINUTE),

    _5m("5m", KlineStepUtil.MINUTE_TYPE,5,KlineStepConstant.STEP_5_MINUTE),

    _15m("15m", KlineStepUtil.MINUTE_TYPE,15,KlineStepConstant.STEP_15_MINUTE),

    _30m("30m", KlineStepUtil.MINUTE_TYPE,30,KlineStepConstant.STEP_30_MINUTE),

    _1H("1H", KlineStepUtil.HOUR_TYPE,1,KlineStepConstant.STEP_1_HOUR),

    _2H("2H", KlineStepUtil.HOUR_TYPE,2,KlineStepConstant.STEP_2_HOUR),

    _4H("4H", KlineStepUtil.HOUR_TYPE,4,KlineStepConstant.STEP_4_HOUR),

    _1D("1D", KlineStepUtil.DAY_TYPE,1,KlineStepConstant.STEP_1_DAY),

    _1W("1W", KlineStepUtil.WEEK_TYPE,1,KlineStepConstant.STEP_1_WEEK),

    _1Month("1Month", KlineStepUtil.MONTH_TYPE,1,KlineStepConstant.STEP_1_MONTH);

    private final String literal;
    private int utilType;
    private int utilStep;
    private int minStep;

    private KlineStep(String literal,int utilType,int utilStep,int minStep) {
        this.literal = literal;
        this.utilType = utilType;
        this.utilStep = utilStep;
        this.minStep = minStep;
    }


    public String getLiteral() {
        return literal;
    }

    public int getUtilType(){
        return utilType;
    }

    public int getUtilStep(){
        return utilStep;
    }

    public int getMinStep(){
        return minStep;
    }

    public static KlineStep get(String value){
        for (KlineStep step : KlineStep.values()){
            if (step.literal.equals(value)){
                return step;
            }
        }
        return null;
    }

    public static KlineStep getByMinStep(int value){
        for (KlineStep step : KlineStep.values()){
            if (step.minStep == value ){
                return step;
            }
        }
        return null;
    }
}
